Feature viewprincipal
cs-leonel-lima/magic-the-gathering pull request #8
Opened 2019-01-23 19:41 UTC by cs-leonel-lima

Ta aí galera, amanha faremos mais mudanças. Então quando der deem o feedback aqui

2019-01-23 21:04 UTC, cs-joao-souza commented on Podfile
> +  pod 'Reusable'
Podfile sem a versão de cada pod. Isso pode ocasionar problemas de versão de swifit

2019-01-23 21:10 UTC, cs-joao-souza commented on magic-the-gathering/Presentation/Scenes/Set List Scene/Datasource and Delegates/CardsCollectionViewDataSource.swift
> +        return itemsDictionary[Array(itemsDictionary.keys).sorted()[section]]?.count ?? 0
Existe uma ordenação em cada chamada de numberOfItemsInSection. Isso infringe um pouco o Single Responsibility porque tem mais de uma responsabilidade esse método. Ele ordena e retorna o count. O ideial é que o array já estivesse ordenado. Além disso está um pouco difícil de entender. Talvez sempre separar e não deixar as coisas aninhadas. Ex:

`
  let orderedArrayKeys = Array(itemsDictionary.keys).sorted()
  let key = orderedArrayKeys[section]
  return itemsDictionary[key].count
`

Assim fica mais fácil de entender.

2019-01-23 21:11 UTC, cs-joao-souza commented on magic-the-gathering/Extensions/UIImageView+Nuke.swift
> +                    placeholder: UIImage(named: "padrequevedo"),
Talvez fosse legal também ou centralizar todas as strings/imagens, ou usar uma lib estilo R.swift ou swiftgen para evitar um String Oriented Protocol.

2019-01-23 21:12 UTC, cs-joao-souza commented on magic-the-gathering/Presentation/Scenes/Set List Scene/CardCollectionView.swift
> +    //swiftlint:disable weak_delegate
Disable de regra de lint no código.

2019-01-23 21:17 UTC, cs-joao-souza commented on magic-the-gathering/Presentation/Scenes/Set List Scene/CardCollectionView.swift
> +    lazy var customDelegate: CardsCollectionViewDelegate = CardsCollectionViewDelegate(delegate: self)
Nome de customDelegate não é muito intuitivo ao longo do código. Talvez alterar o nome para `cardsCollectionViewDelegate`.

Além disso, vi que utilizaram lazy. O lazy é uma instância tardia da variável. Como vocês já estão utilizando a variável direto no construtor, ele não deve ser lazy. Utilizar lazy quando realmente necessário.

Exemplo: você quer mostrar uma tableView quando houver itens e quando não houver, mostrar uma View customizada vazia. Essa View e a tableView podem ser variáveis lazy, porque não necessariamente terá sempre a instância das duas na tela.

2019-01-23 21:18 UTC, cs-joao-souza commented on magic-the-gathering/Presentation/Scenes/Set List Scene/Cells/CardCollectionViewCell.swift
> +        //TODO: Implementar uma lista de corner radius pra cada device
`//TODO: ` também não é uma boa prática. Nunca suba um código com comentário com essa tag. Se deve ser feito daquela maneira, fazer na hora e colocar por exemplo em um backlog de refactoring, onde é possível todo o time ver e alterar futuramente.

2019-01-23 21:21 UTC, cs-joao-souza commented on magic-the-gathering/Presentation/Scenes/Set List Scene/Cells/SetTableViewCell.swift
> +            make.edges.equalTo(self.snp.edges)
```suggestion
            make.edges.equalTo(self.snp.edges)
```

trocar para

```
  make.edges.equalToSuperview()
```

2019-01-23 21:23 UTC, cs-joao-souza commented on magic-the-gathering/Presentation/Scenes/Set List Scene/Datasource and Delegates/CardsCollectionViewDataSource.swift
> +    var collectionView: UICollectionView
```suggestion
    let collectionView: UICollectionView
```

2019-01-23 21:27 UTC, cs-joao-souza commented on magic-the-gathering/Presentation/Scenes/Set List Scene/Datasource and Delegates/CardsCollectionViewDataSource.swift
> +        if let cardsContainer = itemsDictionary[Array(itemsDictionary.keys).sorted()[indexPath.section]] {
Para mim esse cellForRow faz muita coisa. Todas essas regras de negócio ao meu ver deveriam estar dentro da célula.

Sugestão: E se a célula recebesse um opcional do tipo `Card`? 

```
var card: Card? {
    didSet {
         if let card = card {
                textField.text = card.name
                imageView.download(card.url)
         }
    }
}
```

2019-01-23 21:28 UTC, cs-joao-souza commented on magic-the-gathering/Presentation/Scenes/Set List Scene/Datasource and Delegates/CardsCollectionViewDataSource.swift
> +        self.itemsDictionary = CardsManager.categorize(items)
O que acha de injetar esse CardsManager na sua classe? E pensar em tirar esse método estático?

Ou injeta esse CardManager direto, ou abstrai em um protocolo.

Pode ser que com esse método estático aqui, fique um pouco difícil de testar.

2019-01-23 21:30 UTC, cs-joao-souza commented on magic-the-gathering/Presentation/Scenes/Set List Scene/Datasource and Delegates/CardsCollectionViewDelegate.swift
> +    weak var delegate: CardsSelectionDelegate?
Lembro que comentaram na nossa conversa é que o Lint reclama dizendo que o delegate tem que ser optional pq ele tem que ser `weak`. Vale avaliar em algumas circunstâncias se ele n pode ser `unowned`, caso vc n queira que alguém sete ele para `nil` em runtime,

2019-01-23 21:31 UTC, cs-joao-souza commented on magic-the-gathering/Presentation/Scenes/Set List Scene/Datasource and Delegates/SetTableViewDataSource.swift
> +//
CodeStyle: É legal tirar essas escritas que não são utilizadas. O `SwiftFormat` [https://github.com/nicklockwood/SwiftFormat](url) ajuda.

2019-01-23 21:32 UTC, cs-joao-souza commented on magic-the-gathering/Presentation/Scenes/Set List Scene/SetTableViewController.swift
> +        super.init(coder: aDecoder)
Um `fatalError` aqui seria bom. Para evitar métodos que não fazem nada.

2019-01-24 11:58 UTC, cs-adann-simoes commented on magic-the-gathering/Presentation/Scenes/Set List Scene/CardCollectionView.swift
> +    lazy var customDelegate: CardsCollectionViewDelegate = CardsCollectionViewDelegate(delegate: self)
@cs-joao-souza  quando não fazemos essa instância prévia, e colocamos a chamada do delegate direto no construtor, não funciona: 

`self.customDataSource = CardsCollectionViewDataSource(items: [], collectionView: self, delegate: CardsCollectionViewDelegate(delegate: self))`

2019-01-24 12:19 UTC, cs-joao-souza commented on magic-the-gathering/Presentation/Scenes/Set List Scene/CardCollectionView.swift
> +    lazy var customDelegate: CardsCollectionViewDelegate = CardsCollectionViewDelegate(delegate: self)
Sim. Nesse caso que você me mostrou não vai funcionar mesmo porque você está jogando o delegate direto na classe e alguém precisa segurar a instancia do delegate. Ele só é lazy nesse caso porque você precisa passar o self como delegate. Mas ok. Entendi o ponto. 

Podem deixar lazy. =D

2019-01-24 14:41 UTC, cs-adann-simoes commented on magic-the-gathering/Presentation/Scenes/Set List Scene/Datasource and Delegates/CardsCollectionViewDataSource.swift
> +        self.itemsDictionary = CardsManager.categorize(items)
Vamos pensar em refatorar esses código na próxima sprint 👍

2019-01-24 16:43 UTC, cs-gabriel-reynoso requested changes
- Corrijam os testes

2019-01-24 16:50 UTC, cs-isabel-lima commented on magic-the-gathering/Presentation/Scenes/Set List Scene/CardCollectionView.swift
> +    internal var customDataSource: CardsCollectionViewDataSource?
Rename customDataSource to something else like setTableViewDataSource

2019-01-24 20:29 UTC, cs-isabel-lima requested changes

2019-01-24 20:29 UTC, cs-isabel-lima commented on magic-the-gathering/Presentation/Scenes/Set List Scene/CardCollectionView.swift
> +    internal var customDataSource: CardsCollectionViewDataSource?
Rename customDataSource to gain clarity. "setsTableViewDataSource"

2019-01-24 20:29 UTC, cs-isabel-lima commented on magic-the-gathering/Presentation/Scenes/Set List Scene/CardCollectionView.swift
> +extension CardCollectionView: CardsSelectionDelegate {
Rename CardCollectionView to "CardsCollectionView"

2019-01-24 20:29 UTC, cs-isabel-lima commented on magic-the-gathering/Presentation/Scenes/Set List Scene/Datasource and Delegates/CardsCollectionViewDataSource.swift
> +    internal var itemsTuples: [(String, [Card])]
Consider creating a simple Category struct to use instead of this tuples.

2019-01-24 20:29 UTC, cs-isabel-lima commented on magic-the-gathering/Presentation/Scenes/Set List Scene/Datasource and Delegates/CardsCollectionViewDataSource.swift
> +        return itemsTuples[section].1.count
With the struct this would be more clear like `categoriesArray[section].cards.count`

2019-01-28 12:15 UTC, cs-adann-simoes commented on magic-the-gathering/Presentation/Scenes/Set List Scene/Datasource and Delegates/CardsCollectionViewDataSource.swift
> +    internal var itemsTuples: [(String, [Card])]
Vamos deixar para backlog

2019-01-28 12:24 UTC, cs-gabriel-reynoso approved these changes

2019-01-28 12:24 UTC, cs-isabel-lima approved these changes

2019-01-28 12:24 UTC, merged